@startuml

abstract class FuncionarioBase{
  + SalarioBaseStrategy salarioS;
  +ComissaoStrategy comissaoS;
  + float calculaSalario()
}


interface SalarioBaseStrategy{
  + float calculaSalarioBase()
}

class TemSalarioBase extends SalarioBaseStrategy{
  + TemSalarioBase(float base)
  + float calculaSalarioBase()
}


class NaoTemSalarioBase extends SalarioBaseStrategy{
  + float calculaSalarioBase()
}

interface ComissaoStrategy{
  + float calculaComissao(float total)
}

class Comissionado extends ComissaoStrategy {
  + float calculaComissao(float total)
}

class NaoComissionado extends ComissaoStrategy {
  + float calculaComissao(float total)
}

class Vendedor extends IFuncionario{
  +Vendedor()
  +float calculaSalario()
}

class Comprador extends IFuncionario{
  +Comprador()
  +float calculaSalario()
}

class Funcionario extends IFuncionario{
  +Comprador()
  +float calculaSalario()
}

@enduml
