######################################################################
# @author      : Guilherme Wachs Lopes (gwachs@fei.edu.br)
# @file        : Makefile
# @created     : quarta fev 24, 2021 23:13:40 -03
######################################################################

all:
	javac *.java
	java -cp . Main
